name: Build and Publish Binaries

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest]
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: rustup target add ${{ matrix.target }}

      - name: Build Binaries
        run: |
          for bin in dump_paths dump_files; do
            cargo build --release --target ${{ matrix.target }} --bin $bin
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries-${{ needs.build.outputs.platform }}
          path: binaries/${{ needs.build.outputs.platform }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: binaries/*
          token: ${{ secrets.GITHUB_TOKEN }}

